name: Build with make

on:
  push:
    branches: [ master, test-ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [macos-latest]  
    
    env:
      CFLAGS: -Wno-error

    steps:
    - uses: actions/checkout@v2
    - name: cc test
      run: |
        cc --version  
        echo $CFLAGS
        CFLAGS="$CFLAGS -Wno-error"
        echo $CFLAGS 
        cc -Wno-error -o gccvers ./.github/gccvers.c
        ./gccvers
    - name: Configure
      run: ./Configure -dE
    - name: install
      run: mkdir -p $(pwd)/c2man-install
    - name: config
      run: |
        echo "binexp=$(pwd)/c2man-install" >> config.sh
        echo "installprivlib=$(pwd)/c2man-install" >> config.sh
        echo "mansrc=$(pwd)/c2man-install" >> config.sh
    - name: config
      run: |
        sh config_h.SH
        sh flatten.SH
        sh Makefile.SH
    - run: |
        make depend
        make
        make install
